<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>Practice_3_0</RootNamespace>
    <AssemblyName>3.0-Practice</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>CS0649;CS0414;CS0067</NoWarn>
    <HK_PATH Condition="Exists('$(MSBuildProjectDirectory)/.env')">$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/.env').Replace('HK_PATH=', '').Trim())</HK_PATH>
  </PropertyGroup>

  <Target Name="CheckHkPath" BeforeTargets="Build">
    <Error Condition="'$(HK_PATH)' == ''"
           Text="HK_PATH is empty" />
    <Error Condition="!Exists('$(HK_PATH)/Assembly-CSharp.dll')"
           Text="Assembly-CSharp.dll not found in '$(HK_PATH)'. Check your .env file." />
  </Target>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(HK_PATH)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MMHOOK_Assembly-CSharp">
      <HintPath>$(HK_PATH)\MMHOOK_Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>$(HK_PATH)\PlayMaker.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(HK_PATH)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(HK_PATH)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(HK_PATH)\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(HK_PATH)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(HK_PATH)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(HK_PATH)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(HK_PATH)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyMod" AfterTargets="Build">
    <MakeDir Directories="$(HK_PATH)\Mods\3.0 Practice" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFolder="$(HK_PATH)\Mods\3.0 Practice" />
  </Target>
</Project>